### ISSUE TITLE
number of matches between data frames appears to depend on stage order

### ISSUE THREAD

**Issue by tedmoorman** [OlisaNsonwu/diyar#20]
First of all, thank you for working on this package! It fills an important gap.

I'm experiencing some unexpected results in some of my work. The number of matches I get between two data frames appears to be dependent on stage ordering. I've provided a reproducible example.

Here is my data frame: [combined-df.csv](https://github.com/OlisaNsonwu/diyar/files/7179749/combined-df.csv)

Here is my complete code: [number-of-matches-dependent-on-stage-order.txt](https://github.com/OlisaNsonwu/diyar/files/7179767/number-of-matches-dependent-on-stage-order.txt)

Here is a snippet of my code:
```
data_sets = combined_df$data_sets

change_stage_order <- function(attr_1, attr_2, attr_3, attr_4) {
  stages <- list(attr_1 = attr_1, 
                 attr_2 = attr_2, 
                 attr_3 = attr_3, 
                 attr_4 = attr_4)
  
  combined_df$pd1 <- links(criteria = stages, data_source = data_sets, check_duplicates = TRUE, recursive = TRUE, expand = TRUE)
  
  cbind(combined_df, 
        as.data.frame(combined_df$pd1)) %>% 
    select(-pd1) %>% 
    filter(pid_dataset == "data1,data2") %>% 
    nrow()
}
```

Here are my results, where you can see the number of matches change as the stage order changes.
[console-results-from-changing-stage-order.txt](https://github.com/OlisaNsonwu/diyar/files/7179808/console-results-from-changing-stage-order.txt)

Here is the output from ```sessionInfo()```:
```
> sessionInfo()
R version 3.5.3 (2019-03-11)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Red Hat Enterprise Linux Server 7.9 (Maipo)

Matrix products: default
BLAS: /opt/R/R-3.5.3/lib64/R/lib/libRblas.so
LAPACK: /opt/R/R-3.5.3/lib64/R/lib/libRlapack.so

locale:
 [1] LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C               LC_TIME=en_US.UTF-8        LC_COLLATE=en_US.UTF-8    
 [5] LC_MONETARY=en_US.UTF-8    LC_MESSAGES=en_US.UTF-8    LC_PAPER=en_US.UTF-8       LC_NAME=C                 
 [9] LC_ADDRESS=C               LC_TELEPHONE=C             LC_MEASUREMENT=en_US.UTF-8 LC_IDENTIFICATION=C       

attached base packages:
[1] stats     graphics  grDevices datasets  utils     methods   base     

other attached packages:
[1] diyar_0.3.1      fst_0.9.4        dplyr_1.0.7      conflicted_1.0.4

loaded via a namespace (and not attached):
 [1] Rcpp_1.0.7        rstudioapi_0.13   magrittr_2.0.1    tidyselect_1.1.1  R6_2.5.1          rlang_0.4.11     
 [7] fastmap_1.1.0     fansi_0.5.0       tools_3.5.3       parallel_3.5.3    data.table_1.14.0 utf8_1.2.2       
[13] DBI_1.1.1         ellipsis_0.3.2    assertthat_0.2.0  tibble_3.1.4      lifecycle_1.0.0   crayon_1.4.1     
[19] purrr_0.3.4       vctrs_0.3.8       glue_1.4.2        cachem_1.0.1      compiler_3.5.3    pillar_1.6.2     
[25] generics_0.1.0    renv_0.14.0       pkgconfig_2.0.1  
```

Please let me know if I can provide anything else to troubleshoot the issue.

**Comment by OlisaNsonwu** [comment]
This behaviour is expected. It's due to how the "match priority" works.  The excerpt below from `help(links)` explains it; 

```
Match priority decreases with each subsequent stage of the linkage process i.e. earlier stages (criteria) are considered superior. 
Therefore, it's important for each criteria to be listed in an order of decreasing relevance
```

It's also explained a bit further [here](https://olisansonwu.github.io/diyar/articles/links.html#match-priority). Essentially, by switching the order, you're specifying that earlier atrtributes are more relevant as identifiers than the later ones.

See a demo below.

```
library(diyar)
# Stages
stages <- diyar::staff_records[c("surname", "sex")]
stages <- as.list(stages)

# Linkage result based on different ordering i.e. priority or relevance of each stage 
  # Matches in `surname` (stage 1) are prioritised over matching `sex` (stage 2)
p1 <- links(stages)
  # Reversed - Matches in `sex` (stage 1) are prioritised over matching `surname` (stage 2)
p2 <- links(rev(stages))

# Schema diagrams should make it easier to follow
schema(p1, seed = 1, custom_label = ifelse(p1@pid_cri == 1, stages[[1]], stages[[2]]))
schema(p2, seed = 1, custom_label = ifelse(p2@pid_cri == 1, rev(stages)[[1]], rev(stages)[[2]]))
``` 

Also, based on your dataset, having `check_duplicates = FALSE` and `recursive = FALSE` might be more efficient. Reasons explained [here](https://olisansonwu.github.io/diyar/articles/links.html#reduce-the-number-of-records-being-assessed).

Hope you find these useful.

**Comment by tedmoorman** [comment]
Thank you for the quick reply. 

How would I change the syntax to consider all matching criteria as equally relevant? Or, is that not a current feature?

I'm thinking that perhaps I would essentially match on ```sub_criteria```, by assigning vector of 1s for ```criteria```.

At this point, I'm less interested in efficiency and more interested in generating as many matches as possible. I find that the code runs very fast.

**Comment by OlisaNsonwu** [comment]
Yes. That's the way to go however, it will cost a lot in processing time. I recommend skipping/masking records with unique values in every attribute. Their removal will have no impact on the results and it will greatly reduce the runtime.

```
library(dplyr)
library(diyar)

dfr <- read.csv("combined-df.csv") %>%
  as_tibble()

attributes <- as.list(dfr[1:4])
to_skip <- sapply(attributes, function(x) !duplicated(x, fromLast = TRUE) & !duplicated(x, fromLast = FALSE))
to_skip <- rowSums(to_skip) == length(attributes)
to_skip[to_skip] <- NA

dfr$pd <- links(criteria = to_skip,
                data_source = dfr$data_sets,
                sub_criteria = list("cr1" = sub_criteria(dfr$a_id, dfr$b_id, dfr$c_id, dfr$d_id)),
                display = "progress",
                check_duplicates = TRUE,
                recursive = TRUE)

table(decode(dfr$pd@pid_dataset))
summary(dfr$pd)
```

**Comment by tedmoorman** [comment]
That's very helpful. Thank you so much!
