### ISSUE TITLE
Linking multiple record sources

### ISSUE THREAD

**Issue by dennis-wollersheim** [OlisaNsonwu/diyar#21]
Hello Dr Nsonwu

Thanks so much for your work. It seems to be what I search.  I especially like the multistage linkage concept, it allows the integration of domain knowledge into the linkage process.

It seems from the current diyar examples show linkage *within* a single dataset.  Can you provide an example of linkage *between* two datasets?  I have a small dataset that I have to match against larger dataset.  Specifically, I want to find the best candidate from the larger dataset that matches each representative from the smaller set.

Do you suggest that the best solution is to rowbind the 2 datasets together and then use diyar to find the the linkages within?  

Thanks

**Comment by dewoller** [comment]
Following because I posted the above using my alternate github.

**Comment by OlisaNsonwu** [comment]
Hi Dennis. Yes. Once done, you can keep track of the different datasets in the linkage by assigning an identifier to the "data_source" argument.
